#!/bin/bash

echo "Triplet flip"
declare -A triplet 
for (( i=1, i<=50; i++ ))
do
ft=$((RANDOM%6))
case $ft in
	1)
	 ((hhh++))
	triplet [HHH]=$hhh
	;;
	2)
	((hht++))
	triplet[HHT]=$hht
	 ;;
	3)
	((tth++))
	triplet[TTH]=$tth
	;;
	4)
	((ttt++))
	triplet[TTT]=$ttt
	;;
	5)
	((htt++))
	triplet[HTT]=$htt
	;;
	6)
	((tht++))
	triplet[THT]=$tht
	;;
	7)
	((hth++))
	triplet[HTH]=$tht
	;;
	8)
	((hth++))
	triplet[HTH]
	;;

	break
esac

echo  ${!Triplet[@]}

